FROM arm64v8/debian:trixie

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
        debhelper \
        dh-virtualenv \
        python3-dev \
        python3-pip \
        python3-venv \
        libssl-dev \
        libffi-dev \
        libasound2-dev \
        build-essential \
        patchelf \
        git && \
    rm -rf /var/lib/apt/lists/*
