#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd castmasta > /dev/null 2>&1; then
            adduser --system --group \
                --home /var/lib/castmasta \
                --shell /usr/sbin/nologin \
                --no-create-home \
                castmasta
        fi
        mkdir -p /var/lib/castmasta
        chown castmasta:castmasta /var/lib/castmasta
        chmod 700 /var/lib/castmasta
        ;;
esac


# Automatically added by dh_python2:
# dh-virtualenv postinst autoscript
set -e
dh_venv_install_dir='/usr/lib/castmasta'
dh_venv_package='castmasta'

# set to empty to enable verbose output
test "${DH_VERBOSE:-0}" = "1" && DH_VENV_DEBUG="" || DH_VENV_DEBUG=:
$DH_VENV_DEBUG set -x


dh_venv_safe_interpreter_update() {
    # get Python version used
    local pythonX_Y=$(cd "$dh_venv_install_dir/lib" && ls -1d python[2-9].*[0-9] | tail -n1)

    local i
    for i in python ${pythonX_Y%.*} ${pythonX_Y}; do
        local interpreter_path="$dh_venv_install_dir/bin/$i"

        # skip any symlinks, and make sure we have an existing target
        test ! -L "$interpreter_path" || continue
        test -x "$interpreter_path" || continue

        # skip if already identical
        if cmp "/usr/bin/$pythonX_Y" "$interpreter_path" >/dev/null 2>&1; then
            continue
        fi

        # hardlink or copy new interpreter
        cp -fpl "/usr/bin/$pythonX_Y" "$interpreter_path,new" \
            || cp -fp "/usr/bin/$pythonX_Y" "$interpreter_path,new" \
            || rm -f "$interpreter_path,new" \
            || true

        # make a backup (once)
        test -f "$interpreter_path,orig" || ln  "$interpreter_path" "$interpreter_path,orig"

        # atomic move
        if test -x "$interpreter_path,new" && mv "$interpreter_path,new" "$interpreter_path"; then
            echo "Successfully updated $interpreter_path"
        else
            echo >&2 "WARNING: Some error occured while updating $interpreter_path"
        fi
    done
}


case "$1" in
    configure|reconfigure)
        $DH_VENV_DEBUG echo "$0 $1 called with $# args:" "$@"
        dh_venv_safe_interpreter_update
        ;;

    triggered)
        $DH_VENV_DEBUG echo "$0 $1 called with $# args:" "$@"
        for trigger in $2; do
            case "$trigger" in
                /usr/bin/python?.*)
                    # this trigger might be for the "wrong" interpreter (other version),
                    # but the "cmp" in "dh_venv_safe_interpreter_update" and the fact we only
                    # ever look at our own Python version catches that
                    dh_venv_safe_interpreter_update
                    ;;
                dh-virtualenv-interpreter-update)
                    dh_venv_safe_interpreter_update
                    ;;
                *)
                    #echo >&2 "ERROR:" $(basename "$0") "called with unknown trigger '$2'"
                    #exit 1
                    ;;
            esac
        done
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        #echo >&2 "ERROR:" $(basename "$0") "called with unknown argument '$1'"
        #exit 1
        ;;
esac

$DH_VENV_DEBUG set +x
# END dh-virtualenv postinst autoscript

# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'castmasta.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'castmasta.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'castmasta.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'castmasta.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'castmasta.service' >/dev/null || true
	fi
fi
# End automatically added section

